### ISSUE TITLE
Heavy CPU Consuming

### ISSUE THREAD

**Issue by MAAB-FW** [hijam-git/Porda-AI#2]
Turning it on puts a lot of CPU pressure (100%). It is difficult to use on lower config PC. If pressure is applied to the inbuilt GPU, the pressure will be reduced a bit.

**Comment by darkcat-sudo** [comment]
same 100% cpu usage
![Screenshot 2023-09-22 154338](https://github.com/hijam-git/Porda-AI/assets/130399755/456e77d1-3d1a-4862-b6f7-71c61b0560e3)

**Comment by hijam-git** [comment]
Thank you very much. It was experimental. You can increase time delay to reduce CPU usage to 20% or less than it. Please read the documentation.
